name: CI/CD Pipeline for Voting App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Images
      run: |
        docker build -t example-voting-app-vote ./vote
        docker build -t example-voting-app-result ./result
        docker build -t example-voting-app-worker ./worker

    - name: Push Docker Images to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag example-voting-app-vote <your-docker-username>/vote-app:latest
        docker push <your-docker-username>/vote-app:latest

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f k8s-specifications/

